"""add remaining indexes

Revision ID: 06a8372895c1
Revises: b61aac84ce31
Create Date: 2025-04-26 12:02:59.802965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a8372895c1'
down_revision: Union[str, None] = 'b61aac84ce31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_delivery_tasks_created_at'), 'delivery_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_event_type_filter'), 'subscriptions', ['event_type_filter'], unique=False)
    op.create_index(op.f('ix_subscriptions_updated_at'), 'subscriptions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_updated_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_event_type_filter'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_delivery_tasks_created_at'), table_name='delivery_tasks')
    # ### end Alembic commands ###
